[FEATURE] db schema and Order entity
katerinassh/Order-Payment-system pull request #3
Opened 2021-07-28 09:15 UTC by katerinassh

2021-07-29 13:08 UTC, Belakun requested changes

2021-07-29 13:08 UTC, belakun commented on db/migrations/20210727203658_create_orders_table.js
> +    .createTable('products', function(table) {
I assume products shouldn't be stored in orders table. Are we going to have separate table with Order->Product mapping to avoid many-to-many relation?

2021-07-29 15:05 UTC, katerinassh commented on db/migrations/20210727203658_create_orders_table.js
> +    .createTable('products', function(table) {
but it`s creating separate "products" table, so we can use it for additional table product->order

2021-07-30 08:04 UTC, Belakun commented on db/migrations/20210727203658_create_orders_table.js
> +    .createTable('products', function(table) {
weird I thought I saw products column in orders table

2021-07-30 10:59 UTC, Belakun commented
LGTM

2021-07-30 11:20 UTC, merged